name: Branch Name Validation

on:
  pull_request:
    branches:
      - '*' # يشمل جميع الفروع

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # لتحميل الكود من المستودع

      - name: Set script permissions
        run: chmod +x ./.github/scripts/validate-branch-name.sh # إعطاء السكريبت صلاحيات التنفيذ

      - name: Get branch name
        id: get_branch
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "branch=${{ github.head_ref }}" >> $GITHUB_ENV
          else
            echo "branch=${{ github.ref#refs/heads/ }}" >> $GITHUB_ENV
          fi

      - name: Debug branch name
        run: echo "Branch name is: ${{ env.branch }}" # عرض اسم الفرع للتأكد

      - name: Validate Branch Name
        run: ./.github/scripts/validate-branch-name.sh ${{ env.branch }} # تمرير اسم الفرع للسكريبت
