name: Branch Name Validation

on:
  pull_request:
    branches:
      - '*'
jobs:
  validate-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get branch name
        id: get_branch
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "branch=${{ github.head_ref }}" >> $GITHUB_ENV
          else
            echo "branch=${{ github.ref#refs/heads/ }}" >> $GITHUB_ENV
          fi

      - name: Debug branch name
        run: echo "Branch name is:${{ env.branch }}

      - name: Validate Branch Name
        run: ./.github/scripts/validate-branch-name.sh ${{ env.branch }}
